
version: '2.1'
services:
  kykms-mysql:
    image: mahonelau/kykms-mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
      TZ: Asia/Shanghai
    restart: always
    container_name: kykms-mysql
    volumes:
      - /home/docker/data/mysql:/var/lib/mysql
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M
    ports:
    - 3306:3306

  kykms-redis:
    image: redis:5.0
    ports:
    - 6379:6379
    restart: always
    container_name: kykms-redis

  kykms-ES:
    image: mahonelau/kykms-es:latest
    restart: always
    hostname: kykms-ES
    container_name: kykms-ES
    volumes:
      - /home/docker/data/elasticsearch:/usr/share/elasticsearch/data
    ports:
    - 9200:9200
    - 9300:9300
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      cpuset-cpus: 1
      m: 2G

  kykms:
    image: mahonelau/kykms:latest
    restart: always
    container_name: kykms
    volumes:
    - /data/config:/kykms/config
    ports:
    - 8080:8080

  kykms-nginx:
    image: mahonelau/kykms-nginx:latest
    restart: always
    container_name: kykms-nginx
    volumes:
      - /home/docker/data/nginx/conf:/etc/nginx/
      - /home/docker/data/nginx/html:/usr/share/nginx/html
    ports:
    - 3000:3000



