version: '2'
services:
  kykms-mysql:
    build:
      context: ./db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
      TZ: Asia/Shanghai
    restart: always
    container_name: kykms-mysql
    hostname: kykms-mysql
    image: mysql:5.7
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M
#      --default-authentication-plugin=caching_sha2_password
    ports:
      - 3306:3306

  kykms-redis:
    image: redis:5.0
    ports:
      - 6379:6379
    restart: always
    hostname: kykms-redis
    container_name: kykms-redis

  kykms-ES:
    build:
      context: ./ES
    image: elasticsearch:7.6.1
    volumes:
      - /home/docker/data/elasticsearch:/usr/share/elasticsearch/data
    restart: always
    hostname: kykms-ES
    container_name: kykms-ES
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      cpuset-cpus: 1
      m: 2G

  kykms:
    build:
      context: ./jeecg-boot-module-system
    restart: on-failure
    privileged: true
    depends_on:
      - kykms-mysql
      - kykms-redis
      - kykms-ES
    container_name: kykms
    image: kykms
    volumes:
      - /home/docker/data/kykms:/kykms
    hostname: kykms
    ports:
      - 8080:8080
