#### 镜像上传
# 仓库私服： 81.70.17.111:5000
# 第一步：上传镜像到docker仓库
#docker tag kykms-mysql 81.70.17.111:5000/kykms-mysql:1.0
#docker tag kykms 81.70.17.111:5000/kykms:1.0
#docker tag kykms-nginx 81.70.17.111:5000/kykms-nginx:1.0
#docker tag kykms-es 81.70.17.111:5000/kykms-es:1.0

#docker push 81.70.17.111:5000/kykms-mysql:1.0
#docker push 81.70.17.111:5000/kykms:1.0
#docker push 81.70.17.111:5000/kykms-nginx:1.0
#docker push 81.70.17.111:5000/kykms-es:1.0

# 第二步：将此yml文件上传服务器，执行启动命令 docker-compose -f ./docker-compose-server.yml up
version: '2'
services:
  kykms-mysql:
    image: 81.70.17.111:5000/kykms-mysql:1.0
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
    container_name: kykms-mysql
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M
    ports:
    - 3306:3306

  kykms-redis:
    image: redis:5.0
    ports:
    - 6379:6379
    restart: always
    container_name: kykms-redis

  kykms-ES:
    image: 81.70.17.111:5000/kykms-es:1.0
    restart: always
    hostname: kykms-ES
    container_name: kykms-ES
    ports:
    - 9200:9200
    - 9300:9300
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      cpuset-cpus: 1
      m: 2G

  kykms:
    image: 81.70.17.111:5000/kykms:1.0
    restart: always
    container_name: kykms
    volumes:
    - /data/config:/kykms/config
    ports:
    - 8080:8080

  kykms-nginx:
    image: 81.70.17.111:5000/kykms-nginx:1.0
    restart: always
    container_name: kykms-nginx
    ports:
    - 3000:3000