## 商业版试用镜像提供源下载，仅限于个人学习用途，如擅自用于商业用途，带来的一切后果由个人负责
## !!!!暂未完善，如有需求请联系作者!!!!! 直接部署，只支持本机部署和访问，服务端部署需调整参数
##执行启动命令 docker-compose -f ./docker-compose-business.yml up
version: '2'
services:
  kykms-mysql:
    image: mahonelau/kykms-mysql:business
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
      TZ: Asia/Shanghai
    restart: always
    container_name: kykms-mysql
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M
    ports:
    - 3306:3306

  kykms-redis:
    image: redis:5.0
    ports:
    - 6379:6379
    restart: always
    container_name: kykms-redis

  kykms-ES:
    image: mahonelau/kykms-es:business
    restart: always
    hostname: kykms-ES
    container_name: kykms-ES
    ports:
    - 9200:9200
    - 9300:9300
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      cpuset-cpus: 1
      m: 2G

  kykms:
    image: mahonelau/kykms:business
    restart: always
    container_name: kykms
    volumes:
    - /data/config:/kykms/config
    ports:
    - 8080:8080

  kykms-nginx:
    image: mahonelau/kykms-nginx:business
    restart: always
    depends_on:
    - kykms-mysql
    - kykms-redis
    - kykms
    - kykms-ES
    container_name: kykms-nginx
    ports:
    - 3000:3000
